### PR TITLE
feat: add support for spec v1.5

### LINKED ISSUE #109: Specification version 1.5 support
Are there plans to add support for 1.5?

### LINKED ISSUE #115: backward/forward compatibility for Tools (cdx 1.5)
Hi :) 

I've been following the progress of cdx1.5 support in this library for quite some time now. I've noticed tools such as `Trivy` already used in production (`trivy` cli tool).

I wondered about your approach to maintaining compatibility (read/write) for Tools. It's the first time you've had to change the actual field type. Will you use an overriding mechanism, such as implementing UnmarshalJSON and convert `old` slices into the new model?  

The decoding part is much more apparent as `convertTool` would probably be used for this purpose.

Can I work on this solution? I'd like to see a v1.5 compatible version of this library in the stable release.

### PR DESCRIPTION
**Pull request by nscuro**
This PR implements support for version 1.5 of the CycloneDX specification.

### Coverage

See https://github.com/CycloneDX/specification/milestone/6

- [x] https://github.com/CycloneDX/specification/pull/176 (861c43815e04eaa3f77c5f9b3bda52a9ca7e39bd)
- [x] https://github.com/CycloneDX/specification/pull/175 (dcb7270)
- [x] https://github.com/CycloneDX/specification/pull/177 (https://github.com/CycloneDX/cyclonedx-go/commit/56f6336300a371c34c6b17fceb8b6e627bafa2c4)
- [x] https://github.com/CycloneDX/specification/pull/169 (b038935)
- [x] https://github.com/CycloneDX/specification/pull/180 (b7a6c141bc11c668b67eea170013bec81de5cede)
- [x] https://github.com/CycloneDX/specification/pull/181 (b23bd53aace52ecc3c0c4a2ee6fabde23250213f)
- [x] https://github.com/CycloneDX/specification/pull/189 (781a647)
- [x] https://github.com/CycloneDX/specification/pull/190 (9ee6ffd)
- [ ] https://github.com/CycloneDX/specification/pull/194
  - Decoupled to #130 
- [x] https://github.com/CycloneDX/specification/pull/195 (7be18ae)
- [x] https://github.com/CycloneDX/specification/pull/198
- [x] https://github.com/CycloneDX/specification/pull/199 (07a5e86)
- [x] https://github.com/CycloneDX/specification/pull/200 (9f77462)
- [x] https://github.com/CycloneDX/specification/pull/209 (bcf4b6f)
- [x] https://github.com/CycloneDX/specification/pull/224 (5fcf21c)
- [x] https://github.com/CycloneDX/specification/pull/222 (8c9798c)
- [x] https://github.com/CycloneDX/specification/pull/215 (cb23c44)
- [x] https://github.com/CycloneDX/specification/pull/213 (d7e68f3)
- [x] https://github.com/CycloneDX/specification/pull/212 (637efcd)

> **Note**  
> More changes are to come as the spec approaches the v1.5 release.

Closes #109 
Closes #115

### CODE REVIEW

**Comment by wagoodman** [comment]
It looks like all tasks on this PR are completed (merged), does that mean that full support for 1.5 is complete? or is there more work needed?

**Comment by nscuro** [comment]
Hey @wagoodman apologies for the delayed response. You are correct that most features are implemented, however the majority is not merged to `main` yet. The PRs I linked in the description above are from the upstream specification repository (to help me keep track of which features need implementation).

There are some more or less minor tasks outstanding (see #115). Depending on which features of v1.5 you need, perhaps [v0.7.2](https://github.com/CycloneDX/cyclonedx-go/releases/tag/v0.7.2) is sufficient for you already. If you need something that has not been released yet, let me know and I'll see if I can expedite.

**Comment by chris-rock** [comment]
If I see this right, EvidenceOccurrences is missing from 1.5 spec in the implementation.

**Comment by bluesentinelsec** [comment]
@nscuro Hello, I just wanted to raise a demand signal regarding support for the updated `Tools` object.

Do you have an ETA for this at this time?

I know you're habitually busy and don't mean to pile on.

The deprecated `Tools` array is causing one of our services to throw spec-compliance errors, i.e., (_array found, object expected_), so I am just weighing options right now.

**Comment by nscuro** [comment]
Hey @bluesentinelsec thanks for reaching out. Actually I'll have a go at this on the weekend. I am annoyed myself that I haven't yet managed to get this done. I will not promise anything but I'll make an effort to ship at least what has been done so far in this PR, as well as a solution to the `tools` situation.

**Comment by nscuro** [comment]
@chris-rock [`EvidenceOccurrence`](https://cyclonedx.org/docs/1.5/json/#components_items_evidence_occurrences) is already there:

https://github.com/CycloneDX/cyclonedx-go/blob/64eb0c84b3d909db47c5154c17d075f68b0c85ae/cyclonedx.go#L358-L361

**Comment by nscuro** [comment]
Decoupled the last remaining task into https://github.com/CycloneDX/cyclonedx-go/issues/130 to get this PR merged.

**Pull request merged**
